version: '3.8'

services:
  database:
    container_name: aggloDB
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: agglo_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: aggloPHP
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/agglo_project
    depends_on:
      - database

  nginx:
    container_name: agglo_server
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/agglo_project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: database
    depends_on:
      - database



